version: "1.1"
services:
  backend:
    image: saikiran970/my-backend:v1
    ports:
    - "5000:5000"
    env_file:
    - ./backend/.env
    restart: always
  frontend:
    image: saikiran970/my-frontend:v1
    ports:
    - "80:5173"
    env_file:
    - ./frontend/.env
    restart: always

    